- hosts: all
  #user: ansadm
  #become: yes
  #become_method: sudo
  tasks:
       - name: removing  httpd
         yum: name=httpd state=removed
       - name: install httpd
         yum: name=httpd state=installed
       - name: start httpd
         service: name=httpd state=started
       - name: checking service 
         command: "service httpd status"

