- name: Terminate instances
  hosts: localhost
  connection: local
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        region: us-west-2
        state: 'absent'
        instance_ids: i-04f7fcc80d889dde3
