---

# file: setpassword.yml
- hosts: 127.0.0.1
  gather_facts: false
  vars_prompt:
  - name: password
    prompt: "Enter your new password"
  - name: password_verification
    prompt: "Please verify your new password"
  tasks:
  - name: Encrypting provided password
    command: /usr/bin/openssl passwd -1 {{password}}
    register: crypt
    when: password == password_verification


- hosts: all:!127.0.0.1
  gather_facts: false
  sudo: true
  tasks:
  - name: Checking for existing user.
    command: /usr/bin/getent passwd {{username}}
    register: user

  - name: Setting user password.
    user: 
      name={{username}}
      password={{hostvars['127.0.0.1'].crypt.stdout}}
    when: user.rc == 0 and hostvars['127.0.0.1'].crypt.rc == 0 and hostvars['127.0.0.1'].crypt.stdout != ""
