---
- hosts: all
  tasks:
    - name: Make sure that we can connect to the machine
      ping:

    - name: add group "tomcat"
      group: name=tomcat

    - name: add user "tomcat"
      user: name=tomcat group=tomcat createhome=yes
      become: true

    - name: copy Tomcat
    # Please make sure that you must fist copy this tomcat.tar zip file then follow the as its
      copy: src=./apache-tomcat-8.5.51.tar.gz dest=/opt/apache-tomcat-8.5.51.tar.gz
      become: true

    - name: Extract Tomcat archive
      command: tar -zxvf /opt/apache-tomcat-8.5.51.tar.gz -C /opt/ creates=/opt/apache-tomcat-8.5.51
      become: true

    - name: Change ownership of Tomcat installation
      file: path=/opt/apache-tomcat-8.5.51 owner=tomcat group=tomcat state=directory recurse=yes
      become: true

    - name: Configure Tomcat server
      template: src=server.xml dest=/opt/apache-tomcat-8.5.51/conf/
      become: true

    - name: Configure Tomcat users
      template: src=tomcat-users.xml dest=/opt/apache-tomcat-8.5.51/conf/
      become: true

    - name: Stop Tomcat
      command: nohup /opt/apache-tomcat-8.5.51/bin/shutdown.sh
      become: true
      become_user: tomcat

    - name: Start Tomcat
      command: nohup /opt/apache-tomcat-8.5.51/bin/startup.sh
      become: true
      become_user: tomcat

#    - name: wait for tomcat to start
 #     wait_for: port={{http_port}}
  #    become: true


